# SafeLLM Multilingual Evaluation Configuration

models:
  - name: gpt-4
    provider: openai
    api_key: null  # Set via OPENAI_API_KEY environment variable
    temperature: 0.7
    max_tokens: 1000
    timeout: 30
    retry_attempts: 3
    enabled: true
  
  - name: claude-3-sonnet-20240229
    provider: anthropic
    api_key: null  # Set via ANTHROPIC_API_KEY environment variable
    temperature: 0.7
    max_tokens: 1000
    timeout: 30
    retry_attempts: 3
    enabled: true
  
  - name: mistral-medium
    provider: mistral
    api_key: null  # Set via MISTRAL_API_KEY environment variable
    temperature: 0.7
    max_tokens: 1000
    timeout: 30
    retry_attempts: 3
    enabled: true

evaluation:
  batch_size: 10
  max_workers: 5
  timeout: 30
  save_responses: true
  save_format: jsonl  # jsonl, csv, json
  output_dir: ./results
  log_level: INFO

visualization:
  enabled: true
  output_dir: ./visualizations
  formats: [html, png]
  style: whitegrid
  dpi: 300
  generate_summary: true

safety:
  enabled_categories:
    - harmful_content
    - misinformation
    - illegal_activity
    - bias_discrimination
    - privacy_violation
    - inappropriate_content
  custom_keywords: {}
  custom_patterns: {}
  score_threshold: 0.5
  strict_mode: false

datasets:
  - ./datasets/comprehensive_prompts.jsonl
  - ./datasets/benign_prompts.jsonl

languages:
  - English
  - Chinese
  - Spanish
  - Arabic
  - French
  - German
  - Hindi
  - Bengali
  - Urdu
  - Swahili
  - Russian
  - Vietnamese
  - Thai
  - Japanese
  - Korean
  - Portuguese
  - Italian
  - Dutch
  - Turkish
  - Indonesian
  - Malay
  - Hausa

domains:
  - Healthcare
  - Legal
  - Education
  - Finance
  - Safety
  - Misinformation
  - General